{% set name = "herepy" %}
{% set version = "3.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 41e27895057ebfadcafd7e4bf81d06eca696684dbf3a5d87adcbb0a8b2cd5608
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests ==2.25

test:
  imports:
    - herepy

about:
  home: https://github.com/abdullahselek/HerePy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library that provides a Python interface to the HERE APIs
  description: |
    A library that provides a Python interface to the HERE APIs
  doc_url: https://herepy.abdullahselek.com/
  dev_url: https://github.com/abdullahselek/HerePy

extra:
  recipe-maintainers:
    - abdullahselek
