{% set name = "herepy" %}
{% set version = "3.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c299e62e07c9474ac2f231409d295a19f425099abbc577cb9bc4f61443c2618
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - urllib3
    - six
  run:
    - python >=3.8
    - requests ==2.25

test:
  imports:
    - herepy

about:
  home: https://github.com/abdullahselek/HerePy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library that provides a Python interface to the HERE APIs
  description: |
    A library that provides a Python interface to the HERE APIs
  doc_url: https://herepy.abdullahselek.com/
  dev_url: https://github.com/abdullahselek/HerePy

extra:
  recipe-maintainers:
    - abdullahselek
